#!/bin/bash

if [[ $1 == "codegen" ]]
then
   flutter pub run build_runner build --delete-conflicting-outputs
   exit 0
fi

if [[ $1 == "intl-extract-arb" ]]
then
   flutter pub run intl_translation:extract_to_arb --output-dir lib/i18n lib/i18n/app_localizations.dart
   exit 0
fi

if [[ $1 == "intl-generate-dart" ]]
then
   flutter pub run intl_translation:generate_from_arb --output-dir=lib/i18n --no-use-deferred-loading lib/i18n/app_localizations.dart lib/i18n/intl_en.arb lib/i18n/intl_fr.arb lib/i18n/intl_zh_Hans.arb
   exit 0
fi

echo "Available commands intl-extract-arb | intl-generate-dart | codegen"
exit 1