name: arava
description: Arava Flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  super_enum: ^0.4.2
  google_maps_flutter: ^0.5.25+2
  flutter_modular: ^0.5.2
  dio: ^3.0.8
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.6+1
  connectivity: ^0.4.6+2
  flutter_staggered_grid_view: ^0.3.0
  cache_image: ^1.0.5
  sentry: ^3.0.1
  flutter_form_builder: ^3.8.0+1
  package_info: ^0.4.0+14
  device_info: ^0.4.1+5
  flushbar: ^1.9.1
  flutter_rating_bar: ^3.0.1+1
  location: ^2.5.4
  latlong: ^0.6.1
  flutter_sticky_header: ^0.4.2
  collection: ^1.14.11
  expandable: ^4.1.3

dependency_overrides:
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  super_enum_generator: ^0.4.2
  build_runner: ^1.7.3
  json_serializable: ^3.2.0
  analyzer: ^0.39.2
  provider: ^4.0.2
  intl: any
  intl_translation: ^0.17.9
  carousel_slider: ^1.4.1
  bubble_tab_indicator: ^0.1.4
flutter:

  uses-material-design: true

  assets:
    - assets/images/octopus.png
    - assets/images/logo.png
    - assets/images/beach.png
    - assets/images/pin-sponsored.png
    - assets/images/pin.png
    - assets/images/poi-placeholder.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/map_styles/dark.json
    - assets/map_styles/light.json

  fonts:
   - family: CircularStd
     fonts:

     - asset: fonts/CircularStd-Medium.ttf
       weight: 300
     - asset: fonts/CircularStd-MediumItalic.ttf
       weight: 300
       style: italic

     - asset: fonts/CircularStd-Bold.ttf
       weight: 600
     - asset: fonts/CircularStd-BoldItalic.ttf
       style: italic
       weight: 600

     - asset: fonts/CircularStd-Black.ttf
       weight: 700
     - asset: fonts/CircularStd-BlackItalic.ttf
       style: italic
       weight: 700